### ISSUE TITLE
Function definition doesn't work with 0 parameters

### ISSUE THREAD

**Issue by pazzarpj** [pazzarpj/micropython-ustubby#17]
There is an additional opening bracket defined when running no parameters in the function

with
```
import ustubby
def example() -> int:
    pass
ustubby.stub_function(example)
```
```
// No Comment
STATIC mp_obj_t __main___example(() {
    mp_int_t ret_val;

    //Your code here

    return mp_obj_new_int(ret_val);
}
MP_DEFINE_CONST_FUN_OBJ_0(__main___example_obj, __main___example);
```

when it should be
```
// No Comment
STATIC mp_obj_t __main___example() {
    mp_int_t ret_val;

    //Your code here

    return mp_obj_new_int(ret_val);
}
MP_DEFINE_CONST_FUN_OBJ_0(__main___example_obj, __main___example);
```

**Comment by IhorNehrutsa** [comment]
No parameters in the function
[zero_param.zip](https://github.com/pazzarpj/micropython-ustubby/files/5237214/zero_param.zip)
Will this help to test?

**Comment by pazzarpj** [comment]
Thanks it would have.
I dug in and saw what you were trying to do when raising this issue. I'll write some tests when I have some time.
I also have some other stuff I was working on for the path to converting back from c to python but it is a long way off and I want to make any changes also reflected in those functions.
